### ISSUE TITLE
display stays black. 

### ISSUE THREAD

**Issue by TecDroiD** [rdagger/micropython-ssd1322#1]
hi,
my dispay does not react on anything.
I'm using ESP32C3 Supermini for testing.
Is there any way to debug the display connection?

**Comment by rdagger** [comment]
I don’t have an ESP32-C3, but there are 4 likely causes of failure:

1. The wrong SPI pins. A cursory Google search shows the super mini uses GPIO 6 for MOSI and GPIO 4 for SCK.
2. The wrong SPI bus. I think the only available SPI bus on the C3 is SPI 2.
3. The wrong communication protocol is set on the SSD1322 display. Make sure to set the jumpers on the display to SPI as opposed to parallel.
4. The wiring is faulty or too long. SPI is sensitive to wire length and signal integrity.

In theory, the following init should work:
```
spi = SPI(2, baudrate=25000000, sck=Pin(4), mosi=Pin(6))
display = Display(spi, dc=Pin(2), cs=Pin(7), rst=Pin(3))
```

You could also try lowering the baud rate.

![super mini pinout](https://github.com/user-attachments/assets/76d725eb-cdea-4fb5-ab24-bc9173174a37)

**Comment by TecDroiD** [comment]
I think the important information was #3. I got that display without any information on it so I followed the lines and finally found a resistor I removed.. now it works like a charm. Thanks for this lib :)
